-- Initial PostgreSQL/Supabase foundation for Community Book Exchange.
-- No legacy user, catalog, transaction, image, credential, or private data is imported.

create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon, authenticated;

create type public.profile_role as enum (
  'user',
  'admin'
);

create type public.book_status as enum (
  'available',
  'reserved',
  'borrowed',
  'unavailable'
);

create type public.book_condition as enum (
  'new',
  'like_new',
  'good',
  'fair',
  'poor'
);

create type public.request_status as enum (
  'pending',
  'approved',
  'declined',
  'cancelled',
  'expired'
);

create type public.loan_status as enum (
  'active',
  'returned',
  'overdue',
  'cancelled'
);

create type public.notification_type as enum (
  'request_received',
  'request_approved',
  'request_declined',
  'request_cancelled',
  'loan_started',
  'loan_due',
  'loan_returned',
  'system'
);

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null,
  first_name text,
  last_name text,
  phone text,
  city text,
  bio text,
  avatar_path text,
  role public.profile_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_not_blank check (btrim(display_name) <> '')
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  abbreviation text,
  created_at timestamptz not null default now(),
  constraint categories_name_not_blank check (btrim(name) <> ''),
  constraint categories_slug_not_blank check (btrim(slug) <> ''),
  constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table public.books (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles (id) on delete cascade,
  title text not null,
  author text,
  category_id bigint references public.categories (id) on delete set null,
  published_year integer,
  isbn text,
  description text,
  condition public.book_condition,
  status public.book_status not null default 'available',
  cover_path text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint books_title_not_blank check (btrim(title) <> ''),
  constraint books_published_year_reasonable check (
    published_year is null or published_year between 1000 and 2100
  ),
  constraint books_isbn_not_blank check (isbn is null or btrim(isbn) <> '')
);

create table public.book_images (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public.books (id) on delete cascade,
  storage_path text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint book_images_storage_path_not_blank check (btrim(storage_path) <> ''),
  constraint book_images_sort_order_nonnegative check (sort_order >= 0)
);

create table public.borrow_requests (
  id uuid primary key default gen_random_uuid(),
  book_id bigint not null references public.books (id) on delete cascade,
  requester_id uuid not null references public.profiles (id) on delete cascade,
  owner_id uuid not null references public.profiles (id) on delete cascade,
  status public.request_status not null default 'pending',
  message text,
  expires_at timestamptz not null default now() + interval '72 hours',
  responded_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint borrow_requests_participants_differ check (requester_id <> owner_id),
  constraint borrow_requests_message_length check (
    message is null or char_length(message) <= 2000
  ),
  constraint borrow_requests_expiry_after_creation check (expires_at > created_at),
  constraint borrow_requests_responded_after_creation check (
    responded_at is null or responded_at >= created_at
  ),
  constraint borrow_requests_cancelled_after_creation check (
    cancelled_at is null or cancelled_at >= created_at
  )
);

create table public.loans (
  id uuid primary key default gen_random_uuid(),
  request_id uuid unique references public.borrow_requests (id) on delete set null,
  book_id bigint not null references public.books (id) on delete restrict,
  owner_id uuid not null references public.profiles (id) on delete restrict,
  borrower_id uuid not null references public.profiles (id) on delete restrict,
  status public.loan_status not null default 'active',
  started_at timestamptz not null default now(),
  due_at timestamptz not null default now() + interval '21 days',
  returned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint loans_participants_differ check (borrower_id <> owner_id),
  constraint loans_due_after_start check (due_at > started_at),
  constraint loans_returned_after_start check (
    returned_at is null or returned_at >= started_at
  ),
  constraint loans_returned_status_consistent check (
    status <> 'returned' or returned_at is not null
  )
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  type public.notification_type not null,
  title text not null,
  body text,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint notifications_title_not_blank check (btrim(title) <> ''),
  constraint notifications_data_is_object check (jsonb_typeof(data) = 'object')
);

-- Foreign-key, RLS, and common workflow indexes.
create index books_owner_id_idx on public.books (owner_id);
create index books_category_id_idx on public.books (category_id);
create index books_active_status_created_at_idx
  on public.books (status, created_at desc)
  where is_active;

create index book_images_book_id_sort_order_idx
  on public.book_images (book_id, sort_order, id);

create index borrow_requests_book_id_idx on public.borrow_requests (book_id);
create index borrow_requests_requester_id_idx on public.borrow_requests (requester_id);
create index borrow_requests_owner_id_idx on public.borrow_requests (owner_id);
create unique index borrow_requests_one_pending_per_requester_book_idx
  on public.borrow_requests (requester_id, book_id)
  where status = 'pending';
create index borrow_requests_owner_status_created_at_idx
  on public.borrow_requests (owner_id, status, created_at desc);
create index borrow_requests_requester_status_created_at_idx
  on public.borrow_requests (requester_id, status, created_at desc);

create index loans_book_id_idx on public.loans (book_id);
create index loans_owner_id_idx on public.loans (owner_id);
create index loans_borrower_id_idx on public.loans (borrower_id);
create unique index loans_one_active_per_book_idx
  on public.loans (book_id)
  where status in ('active', 'overdue');
create index loans_owner_status_due_at_idx
  on public.loans (owner_id, status, due_at);
create index loans_borrower_status_due_at_idx
  on public.loans (borrower_id, status, due_at);

create index notifications_user_created_at_idx
  on public.notifications (user_id, created_at desc);
create index notifications_user_unread_created_at_idx
  on public.notifications (user_id, created_at desc)
  where read_at is null;

-- Trigger helpers live in a non-exposed schema.
create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public, anon, authenticated;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger books_set_updated_at
before update on public.books
for each row execute function private.set_updated_at();

create trigger borrow_requests_set_updated_at
before update on public.borrow_requests
for each row execute function private.set_updated_at();

create trigger loans_set_updated_at
before update on public.loans
for each row execute function private.set_updated_at();

-- SECURITY DEFINER is required because an auth trigger must insert a profile
-- before the new user can hold normal application privileges.
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_display_name text;
begin
  v_display_name := coalesce(
    nullif(btrim(new.raw_user_meta_data ->> 'display_name'), ''),
    nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''),
    'Community member'
  );

  insert into public.profiles (id, display_name)
  values (new.id, v_display_name);

  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

-- SECURITY DEFINER is required so request ownership is derived from the book
-- and cannot be forged by a client. The trigger also fixes requester_id to auth.uid().
create or replace function private.prepare_borrow_request()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_actor_id uuid;
  v_owner_id uuid;
begin
  v_actor_id := (select auth.uid());

  if v_actor_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select b.owner_id
  into v_owner_id
  from public.books as b
  where b.id = new.book_id
    and b.is_active
    and b.status = 'available';

  if v_owner_id is null then
    raise exception 'The book is not available for requests.' using errcode = 'P0001';
  end if;

  if v_owner_id = v_actor_id then
    raise exception 'A user cannot request their own book.' using errcode = '23514';
  end if;

  new.requester_id := v_actor_id;
  new.owner_id := v_owner_id;
  new.status := 'pending';
  new.expires_at := now() + interval '72 hours';
  new.responded_at := null;
  new.cancelled_at := null;

  return new;
end;
$$;

revoke all on function private.prepare_borrow_request() from public, anon, authenticated;

create trigger borrow_requests_prepare_insert
before insert on public.borrow_requests
for each row execute function private.prepare_borrow_request();

-- SECURITY DEFINER is required because clients cannot insert notifications.
create or replace function private.notify_borrow_request_created()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  insert into public.notifications (user_id, type, title, body, data)
  values (
    new.owner_id,
    'request_received',
    'New book request',
    'A community member requested one of your books.',
    jsonb_build_object('request_id', new.id, 'book_id', new.book_id)
  );

  return new;
end;
$$;

revoke all on function private.notify_borrow_request_created() from public, anon, authenticated;

create trigger borrow_requests_notify_owner
after insert on public.borrow_requests
for each row execute function private.notify_borrow_request_created();

-- SECURITY DEFINER is necessary for this atomic transition because clients
-- cannot create loans, alter workflow-controlled book status, or notify users.
create or replace function public.approve_borrow_request(p_request_id uuid)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_actor_id uuid;
  v_book_id bigint;
  v_request public.borrow_requests%rowtype;
  v_book public.books%rowtype;
  v_loan_id uuid;
begin
  v_actor_id := (select auth.uid());

  if v_actor_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select br.book_id
  into v_book_id
  from public.borrow_requests as br
  where br.id = p_request_id;

  if v_book_id is null then
    raise exception 'Request not found.' using errcode = 'P0002';
  end if;

  -- All approval transactions lock the book before the request.
  select b.*
  into v_book
  from public.books as b
  where b.id = v_book_id
  for update;

  select br.*
  into v_request
  from public.borrow_requests as br
  where br.id = p_request_id
  for update;

  if v_request.owner_id <> v_actor_id
     or v_book.owner_id <> v_actor_id
     or v_request.owner_id <> v_book.owner_id then
    raise exception 'Only the current book owner can approve this request.' using errcode = '42501';
  end if;

  if v_request.status <> 'pending' then
    raise exception 'Only pending requests can be approved.' using errcode = 'P0001';
  end if;

  if v_request.expires_at <= now() then
    raise exception 'This request has expired.' using errcode = 'P0001';
  end if;

  if not v_book.is_active or v_book.status <> 'available' then
    raise exception 'The book is no longer available.' using errcode = 'P0001';
  end if;

  if exists (
    select 1
    from public.loans as l
    where l.book_id = v_book.id
      and l.status in ('active', 'overdue')
  ) then
    raise exception 'The book already has an active loan.' using errcode = '23505';
  end if;

  update public.borrow_requests
  set status = 'approved',
      responded_at = now()
  where id = v_request.id;

  insert into public.loans (
    request_id,
    book_id,
    owner_id,
    borrower_id,
    status,
    started_at,
    due_at
  )
  values (
    v_request.id,
    v_book.id,
    v_book.owner_id,
    v_request.requester_id,
    'active',
    now(),
    now() + interval '21 days'
  )
  returning id into v_loan_id;

  update public.books
  set status = 'borrowed'
  where id = v_book.id;

  with declined as (
    update public.borrow_requests
    set status = 'declined',
        responded_at = now()
    where book_id = v_book.id
      and id <> v_request.id
      and status = 'pending'
    returning requester_id, id
  )
  insert into public.notifications (user_id, type, title, body, data)
  select
    declined.requester_id,
    'request_declined',
    'Book request declined',
    'The book is no longer available.',
    jsonb_build_object('request_id', declined.id, 'book_id', v_book.id)
  from declined;

  insert into public.notifications (user_id, type, title, body, data)
  values
    (
      v_request.requester_id,
      'request_approved',
      'Book request approved',
      'The owner approved your request.',
      jsonb_build_object('request_id', v_request.id, 'loan_id', v_loan_id, 'book_id', v_book.id)
    ),
    (
      v_request.requester_id,
      'loan_started',
      'Loan started',
      'Your 21-day loan has started.',
      jsonb_build_object('loan_id', v_loan_id, 'book_id', v_book.id)
    ),
    (
      v_book.owner_id,
      'loan_started',
      'Loan started',
      'A 21-day loan has started for your book.',
      jsonb_build_object('loan_id', v_loan_id, 'book_id', v_book.id)
    );

  return v_loan_id;
end;
$$;

create or replace function public.decline_borrow_request(p_request_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_actor_id uuid;
  v_request public.borrow_requests%rowtype;
begin
  v_actor_id := (select auth.uid());

  if v_actor_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select br.*
  into v_request
  from public.borrow_requests as br
  where br.id = p_request_id
  for update;

  if not found then
    raise exception 'Request not found.' using errcode = 'P0002';
  end if;

  if v_request.owner_id <> v_actor_id then
    raise exception 'Only the book owner can decline this request.' using errcode = '42501';
  end if;

  if v_request.status <> 'pending' then
    raise exception 'Only pending requests can be declined.' using errcode = 'P0001';
  end if;

  if v_request.expires_at <= now() then
    raise exception 'This request has expired.' using errcode = 'P0001';
  end if;

  update public.borrow_requests
  set status = 'declined',
      responded_at = now()
  where id = v_request.id;

  insert into public.notifications (user_id, type, title, body, data)
  values (
    v_request.requester_id,
    'request_declined',
    'Book request declined',
    'The owner declined your request.',
    jsonb_build_object('request_id', v_request.id, 'book_id', v_request.book_id)
  );
end;
$$;

create or replace function public.cancel_borrow_request(p_request_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_actor_id uuid;
  v_request public.borrow_requests%rowtype;
begin
  v_actor_id := (select auth.uid());

  if v_actor_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select br.*
  into v_request
  from public.borrow_requests as br
  where br.id = p_request_id
  for update;

  if not found then
    raise exception 'Request not found.' using errcode = 'P0002';
  end if;

  if v_request.requester_id <> v_actor_id then
    raise exception 'Only the requester can cancel this request.' using errcode = '42501';
  end if;

  if v_request.status <> 'pending' then
    raise exception 'Only pending requests can be cancelled.' using errcode = 'P0001';
  end if;

  update public.borrow_requests
  set status = 'cancelled',
      cancelled_at = now()
  where id = v_request.id;

  insert into public.notifications (user_id, type, title, body, data)
  values (
    v_request.owner_id,
    'request_cancelled',
    'Book request cancelled',
    'A requester cancelled their pending request.',
    jsonb_build_object('request_id', v_request.id, 'book_id', v_request.book_id)
  );
end;
$$;

create or replace function public.return_loan(p_loan_id uuid)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_actor_id uuid;
  v_loan public.loans%rowtype;
begin
  v_actor_id := (select auth.uid());

  if v_actor_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select l.*
  into v_loan
  from public.loans as l
  where l.id = p_loan_id
  for update;

  if not found then
    raise exception 'Loan not found.' using errcode = 'P0002';
  end if;

  if v_actor_id <> v_loan.owner_id and v_actor_id <> v_loan.borrower_id then
    raise exception 'Only a loan participant can mark it returned.' using errcode = '42501';
  end if;

  if v_loan.status <> 'active' and v_loan.status <> 'overdue' then
    raise exception 'Only an active or overdue loan can be returned.' using errcode = 'P0001';
  end if;

  update public.loans
  set status = 'returned',
      returned_at = now()
  where id = v_loan.id;

  update public.books
  set status = 'available'
  where id = v_loan.book_id
    and owner_id = v_loan.owner_id;

  insert into public.notifications (user_id, type, title, body, data)
  values
    (
      v_loan.owner_id,
      'loan_returned',
      'Book returned',
      'The loan has been marked returned.',
      jsonb_build_object('loan_id', v_loan.id, 'book_id', v_loan.book_id)
    ),
    (
      v_loan.borrower_id,
      'loan_returned',
      'Book returned',
      'The loan has been marked returned.',
      jsonb_build_object('loan_id', v_loan.id, 'book_id', v_loan.book_id)
    );
end;
$$;

revoke all on function public.approve_borrow_request(uuid) from public, anon;
revoke all on function public.decline_borrow_request(uuid) from public, anon;
revoke all on function public.cancel_borrow_request(uuid) from public, anon;
revoke all on function public.return_loan(uuid) from public, anon;

grant execute on function public.approve_borrow_request(uuid) to authenticated;
grant execute on function public.decline_borrow_request(uuid) to authenticated;
grant execute on function public.cancel_borrow_request(uuid) to authenticated;
grant execute on function public.return_loan(uuid) to authenticated;

-- Row Level Security is enabled before any application or private data exists.
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.books enable row level security;
alter table public.book_images enable row level security;
alter table public.borrow_requests enable row level security;
alter table public.loans enable row level security;
alter table public.notifications enable row level security;

create policy profiles_select_own
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

create policy profiles_update_own
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy categories_select_public
on public.categories
for select
to anon, authenticated
using (true);

create policy books_select_active_public
on public.books
for select
to anon, authenticated
using (is_active);

create policy books_select_own
on public.books
for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy books_insert_own
on public.books
for insert
to authenticated
with check (
  (select auth.uid()) = owner_id
  and status = 'available'
  and is_active
);

create policy books_update_own
on public.books
for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy books_delete_own
on public.books
for delete
to authenticated
using ((select auth.uid()) = owner_id);

create policy book_images_select_active_public
on public.book_images
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.books as b
    where b.id = book_images.book_id
      and b.is_active
  )
);

create policy book_images_select_owned_book
on public.book_images
for select
to authenticated
using (
  exists (
    select 1
    from public.books as b
    where b.id = book_images.book_id
      and b.owner_id = (select auth.uid())
  )
);

create policy book_images_insert_owned_book
on public.book_images
for insert
to authenticated
with check (
  exists (
    select 1
    from public.books as b
    where b.id = book_images.book_id
      and b.owner_id = (select auth.uid())
  )
);

create policy book_images_update_owned_book
on public.book_images
for update
to authenticated
using (
  exists (
    select 1
    from public.books as b
    where b.id = book_images.book_id
      and b.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.books as b
    where b.id = book_images.book_id
      and b.owner_id = (select auth.uid())
  )
);

create policy book_images_delete_owned_book
on public.book_images
for delete
to authenticated
using (
  exists (
    select 1
    from public.books as b
    where b.id = book_images.book_id
      and b.owner_id = (select auth.uid())
  )
);

create policy borrow_requests_select_requester
on public.borrow_requests
for select
to authenticated
using ((select auth.uid()) = requester_id);

create policy borrow_requests_select_owner
on public.borrow_requests
for select
to authenticated
using ((select auth.uid()) = owner_id);

create policy borrow_requests_insert_requester
on public.borrow_requests
for insert
to authenticated
with check (
  (select auth.uid()) = requester_id
  and requester_id <> owner_id
  and status = 'pending'
  and exists (
    select 1
    from public.books as b
    where b.id = borrow_requests.book_id
      and b.owner_id = borrow_requests.owner_id
      and b.owner_id <> (select auth.uid())
      and b.is_active
      and b.status = 'available'
  )
);

create policy loans_select_participants
on public.loans
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or (select auth.uid()) = borrower_id
);

create policy notifications_select_own
on public.notifications
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy notifications_update_own_read_state
on public.notifications
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- Explicit Data API grants. RLS remains the row-level authorization boundary.
grant usage on schema public to anon, authenticated;

grant select on public.categories to anon, authenticated;
grant select on public.books to anon, authenticated;
grant select on public.book_images to anon, authenticated;

grant select on public.profiles to authenticated;
grant update (
  display_name,
  first_name,
  last_name,
  phone,
  city,
  bio,
  avatar_path
) on public.profiles to authenticated;

grant insert (
  owner_id,
  title,
  author,
  category_id,
  published_year,
  isbn,
  description,
  condition,
  cover_path
) on public.books to authenticated;
grant update (
  title,
  author,
  category_id,
  published_year,
  isbn,
  description,
  condition,
  cover_path,
  is_active
) on public.books to authenticated;
grant delete on public.books to authenticated;

grant insert, update, delete on public.book_images to authenticated;
grant select on public.borrow_requests to authenticated;
grant insert (book_id, message) on public.borrow_requests to authenticated;
grant select on public.loans to authenticated;
grant select on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;

grant usage, select on sequence public.books_id_seq to authenticated;
grant usage, select on sequence public.book_images_id_seq to authenticated;

-- Service-role privileges are explicit but no service-role key is retrieved or stored.
grant all on public.profiles to service_role;
grant all on public.categories to service_role;
grant all on public.books to service_role;
grant all on public.book_images to service_role;
grant all on public.borrow_requests to service_role;
grant all on public.loans to service_role;
grant all on public.notifications to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.categories (name, slug)
values
  ('Math', 'math'),
  ('Science', 'science'),
  ('Horror', 'horror'),
  ('Action', 'action'),
  ('Fantasy', 'fantasy'),
  ('Grammar', 'grammar'),
  ('Other / Uncategorized', 'other-uncategorized')
on conflict (slug) do nothing;
