-- Schema-only foundation for preserving legacy members, categories, books,
-- and original ownership without importing personal or catalog data.

create table private.legacy_members (
  id bigint generated by default as identity primary key,
  legacy_user_id integer not null unique,
  claimed_profile_id uuid references public.profiles (id) on delete set null,
  source_created_on date,
  first_name text,
  last_name text,
  display_name_candidate text,
  legacy_username text,
  legacy_email text,
  normalized_email text generated always as (lower(btrim(legacy_email))) stored,
  phone text,
  legacy_user_status text,
  legacy_address_id bigint,
  street_name text,
  address_city text,
  postal_code text,
  claim_status text not null,
  claimed_at timestamptz,
  source_row_hash text not null,
  imported_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint legacy_members_claim_status_valid check (
    claim_status in ('unclaimed', 'review_required', 'claimed')
  ),
  constraint legacy_members_claim_state_consistent check (
    (
      claim_status = 'claimed'
      and claimed_profile_id is not null
      and claimed_at is not null
    )
    or
    (
      claim_status in ('unclaimed', 'review_required')
      and claimed_profile_id is null
      and claimed_at is null
    )
  ),
  constraint legacy_members_source_row_hash_not_blank check (
    btrim(source_row_hash) <> ''
  )
);

create index legacy_members_normalized_email_idx
  on private.legacy_members (normalized_email)
  where normalized_email is not null;

create unique index legacy_members_claimed_profile_id_key
  on private.legacy_members (claimed_profile_id)
  where claimed_profile_id is not null;

create index legacy_members_claim_status_idx
  on private.legacy_members (claim_status);

create table private.legacy_category_map (
  legacy_category_id integer primary key,
  category_id bigint not null references public.categories (id) on delete restrict,
  legacy_name text,
  legacy_abbreviation text,
  mapping_reason text not null,
  source_row_hash text,
  imported_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint legacy_category_map_mapping_reason_not_blank check (
    btrim(mapping_reason) <> ''
  ),
  constraint legacy_category_map_source_row_hash_not_blank check (
    source_row_hash is null or btrim(source_row_hash) <> ''
  )
);

create index legacy_category_map_category_id_idx
  on private.legacy_category_map (category_id);

alter table public.books
  drop constraint books_owner_id_fkey;

alter table public.books
  alter column owner_id drop not null,
  add constraint books_owner_id_fkey
    foreign key (owner_id)
    references public.profiles (id)
    on delete set null,
  add column source_kind text not null default 'native',
  add column owner_display_name text not null default 'Community member',
  add constraint books_source_kind_valid check (
    source_kind in ('native', 'legacy')
  ),
  add constraint books_native_owner_required check (
    source_kind = 'legacy' or owner_id is not null
  ),
  add constraint books_owner_display_name_not_blank check (
    btrim(owner_display_name) <> ''
  );

create table private.legacy_book_links (
  legacy_book_id bigint primary key,
  book_id bigint not null unique
    references public.books (id) on delete cascade,
  legacy_owner_user_id integer not null,
  legacy_member_id bigint
    references private.legacy_members (id) on delete restrict,
  legacy_category_id integer,
  legacy_status_id integer,
  legacy_barcode text,
  source_row_hash text not null,
  imported_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint legacy_book_links_source_row_hash_not_blank check (
    btrim(source_row_hash) <> ''
  )
);

create index legacy_book_links_legacy_member_id_idx
  on private.legacy_book_links (legacy_member_id);

create index legacy_book_links_legacy_category_id_idx
  on private.legacy_book_links (legacy_category_id);

create trigger legacy_members_set_updated_at
before update on private.legacy_members
for each row execute function private.set_updated_at();

create trigger legacy_category_map_set_updated_at
before update on private.legacy_category_map
for each row execute function private.set_updated_at();

create trigger legacy_book_links_set_updated_at
before update on private.legacy_book_links
for each row execute function private.set_updated_at();
